language: php
cache:
  bundler: true
  apt: true
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
sudo: false

before_install:
  - export UPDATE TRAVIS_BUILD_DIR
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - EXIT_VALUE=0
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
  - git clone https://github.com/acquia/lightning.git lightning
  - cd lightning
  - git checkout 7927a1496ec131463f25a9bf1a1d668bba8a3696
  - drush make --concurrency=5 build-lightning.make ../drupal -y
  - cd ../drupal
  - git clone https://github.com/balsama/d8contrib.git modules/d8contrib
  - drush make --no-core -y modules/d8contrib/d8contrib.make.yml
  - php modules/composer_manager/scripts/init.php
  - composer drupal-update commerceguys/intl commerceguys/addressing commerceguys/zone mikehaertl/phpwkhtmltopdf league/csv simplesamlphp/simplesamlphp
  - composer require cebe/markdown
  - drush si lightning --db-url=mysql://root:@localhost/drupal -y

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - drush en -y d8contrib
  - mv modules/d8contrib/d8contrib_tests d8contrib_tests
  - cd d8contrib_tests
  - touch behat.local.yml
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.1.jar"
  - "java -jar selenium-server-standalone-2.48.1.jar > /dev/null &"
  - sleep 5
  - composer install

script:
  - bin/behat --tags=d8contrib
